@startuml
title Components — Modular Monolith (Jakarta EE on WildFly)
skinparam componentStyle rectangle
skinparam defaultFontName "DejaVu Sans"

actor Resident
actor Driver
actor Dispatcher

package "WMIS Monolith" {
  [API (JAX-RS)] <<Presentation>>
  [Intake Application] <<UseCases>>
  [Routing Application] <<UseCases>>
  [Execution Application] <<UseCases>>
  [Adjustment Application] <<UseCases>>
  [Domain] <<Core Domain>>
  [Persistence JPA] <<Adapter>>
  [Map Adapter] <<Adapter>>
  [Telematics Adapter] <<Adapter>>
  [Printing Adapter] <<Adapter>>
  [Identity/OIDC] <<Infra>>
  [Outbox] <<Infra>>
  database "PostgreSQL" as PG
}

Resident --> [API (JAX-RS)]
Driver --> [API (JAX-RS)]
Dispatcher --> [API (JAX-RS)]

[API (JAX-RS)] --> [Intake Application]
[API (JAX-RS)] --> [Routing Application]
[API (JAX-RS)] --> [Execution Application]
[API (JAX-RS)] --> [Adjustment Application]

[Intake Application] --> [Domain]
[Routing Application] --> [Domain]
[Execution Application] --> [Domain]
[Adjustment Application] --> [Domain]

[Intake Application] ..> [Persistence JPA]
[Routing Application] ..> [Persistence JPA]
[Execution Application] ..> [Persistence JPA]

[Routing Application] ..> [Map Adapter]
[Execution Application] ..> [Telematics Adapter]
[Intake Application] ..> [Printing Adapter]

[Persistence JPA] --> PG
[Outbox] --> PG
@enduml
