@startuml
title Deployment — Edge & Cloud
node "Edge Site (Пункт приёма)" {
  node "Kiosk Box" {
    [POS App]
    artifact "Весы" as Scales
    artifact "Фискальный принтер" as FP
  }
}
node "Cloud/K8s" {
  node "Cluster" {
    [API Gateway Pod]
    [Waste Core Pod]
    [Billing Pod]
    [Reporting Pod]
  }
  database "PostgreSQL (HA)" as PG
  queue "Kafka" as MQ
}
[POS App] --> [API Gateway Pod] : HTTPS mTLS
[POS App] --> Scales : RS-232/USB/TCP
[POS App] --> FP : ESC/POS
[API Gateway Pod] --> [Waste Core Pod]
[Waste Core Pod] --> PG
[Waste Core Pod] --> MQ
[Reporting Pod] <.. MQ
@enduml
