-- DROP SCHEMA public CASCADE;
-- CREATE SCHEMA public;

DROP TABLE IF EXISTS incidents CASCADE;
DROP TABLE IF EXISTS stop_events CASCADE;
DROP TABLE IF EXISTS route_stops CASCADE;
DROP TABLE IF EXISTS routes CASCADE;
DROP TABLE IF EXISTS driver_shifts CASCADE;
DROP TABLE IF EXISTS kiosk_orders CASCADE;
DROP TABLE IF EXISTS garbage_point_fractions CASCADE;
DROP TABLE IF EXISTS garbage_points CASCADE;
DROP TABLE IF EXISTS container_sizes CASCADE;
DROP TABLE IF EXISTS fractions CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS incident_type CASCADE;
DROP TYPE IF EXISTS stop_event_type CASCADE;
DROP TYPE IF EXISTS stop_status CASCADE;
DROP TYPE IF EXISTS route_status CASCADE;
DROP TYPE IF EXISTS shift_status CASCADE;
DROP TYPE IF EXISTS container_size_code CASCADE;
DROP TYPE IF EXISTS order_status CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;

DROP FUNCTION IF EXISTS route_stops_autoseq() CASCADE;
DROP FUNCTION IF EXISTS incidents_touch() CASCADE;
DROP FUNCTION IF EXISTS incidents_after_insert() CASCADE;
DROP FUNCTION IF EXISTS incidents_after_update() CASCADE;
DROP FUNCTION IF EXISTS routes_validate_start() CASCADE;
